"""
api/app.py — FastAPI application factory for the RFP Analyzer.

Run (development):
    uvicorn api.app:app --reload --port 8000

Run (production):
    uvicorn api.app:app --host 0.0.0.0 --port 8000 --workers 4

Interactive API docs (auto-generated by FastAPI):
    http://localhost:8000/docs        ← Swagger UI
    http://localhost:8000/redoc       ← ReDoc

Preferences form:
    http://localhost:8000/            ← HTML intake form
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles

from router import router
from gse_template_api import router as gsc_router

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
)
logger = logging.getLogger(__name__)

# ── HTML form (served at /) ───────────────────────────────────────────────────
# Inlined so the module is self-contained — no separate static dir needed.
# The form POSTs JSON to /api/preferences, then /api/analyze.

_HTML_FORM = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>RFP Analyzer — Scoping Preferences</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  :root {
    --bg:#fafaf9; --surface:#ffffff; --border:#e5e3da; --text:#1a1916;
    --muted:#6b6a65; --accent:#185FA5; --accent-bg:#e6f1fb;
    --success-bg:#eaf3de; --success:#3B6D11;
    --radius:10px; --radius-sm:6px;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
  }
  body { background:var(--bg); color:var(--text); min-height:100vh; }
  .shell { max-width:720px; margin:0 auto; padding:2rem 1.5rem 4rem; }
  .page-header { margin-bottom:2rem; }
  .page-header h1 { font-size:22px; font-weight:500; }
  .page-header p { font-size:14px; color:var(--muted); margin-top:5px; line-height:1.6; }
  .step { display:none; } .step.active { display:block; }
  .step-label { font-size:11px; font-weight:500; letter-spacing:.07em; text-transform:uppercase; color:var(--muted); margin-bottom:6px; }
  .step-title { font-size:18px; font-weight:500; margin-bottom:5px; }
  .step-desc { font-size:14px; color:var(--muted); line-height:1.6; margin-bottom:1.5rem; }
  .section { margin-bottom:1.5rem; }
  .section-label { font-size:13px; font-weight:500; margin-bottom:10px; color:var(--text); }
  .option-grid { display:grid; grid-template-columns:repeat(auto-fit, minmax(145px,1fr)); gap:8px; }
  .opt { border:1px solid var(--border); border-radius:var(--radius-sm); padding:11px 13px;
         cursor:pointer; background:var(--surface); transition:border-color .12s; }
  .opt:hover { border-color:#b5b3a8; }
  .opt.selected { border:2px solid var(--accent); background:var(--accent-bg); }
  .opt-label { font-size:13px; font-weight:500; line-height:1.3; }
  .opt.selected .opt-label { color:var(--accent); }
  .opt-sub { font-size:11px; color:var(--muted); margin-top:3px; line-height:1.4; }
  .opt.selected .opt-sub { color:var(--accent); opacity:.75; }
  .tag-row { display:flex; flex-wrap:wrap; gap:7px; }
  .tag { font-size:12px; padding:5px 13px; border-radius:20px; border:1px solid var(--border);
         cursor:pointer; background:var(--surface); color:var(--muted); transition:all .12s; user-select:none; }
  .tag:hover { border-color:#b5b3a8; color:var(--text); }
  .tag.selected { background:var(--accent-bg); color:var(--accent); border-color:var(--accent); font-weight:500; }
  .divider { height:1px; background:var(--border); margin:1.5rem 0; }
  .text-input { width:100%; font-size:13px; padding:9px 12px; border:1px solid var(--border);
                border-radius:var(--radius-sm); background:var(--surface); color:var(--text); }
  .text-input:focus { outline:2px solid var(--accent); outline-offset:1px; border-color:transparent; }
  .info-note { font-size:12px; color:var(--muted); padding:8px 11px; background:#f5f4f0;
               border-radius:var(--radius-sm); margin-top:8px; line-height:1.5; }
  .conditional { border:1px solid var(--border); border-radius:var(--radius-sm);
                 padding:13px 15px; background:#f9f8f5; margin-top:10px; display:none; }
  .conditional.visible { display:block; }
  .conditional .section-label { font-size:12px; color:var(--muted); }
  .btn-row { display:flex; justify-content:space-between; align-items:center; margin-top:1.5rem; gap:12px; }
  .btn { padding:9px 22px; font-size:14px; font-weight:500; border-radius:var(--radius-sm);
         cursor:pointer; border:1px solid var(--border); background:var(--surface); color:var(--text); transition:background .12s; }
  .btn:hover { background:#f5f4f0; }
  .btn-primary { background:var(--text); color:#fff; border-color:var(--text); }
  .btn-primary:hover { background:#333; }
  .btn-primary:disabled { background:#999; border-color:#999; cursor:not-allowed; }
  .btn-ghost { font-size:13px; color:var(--muted); cursor:pointer; background:none; border:none;
               display:flex; align-items:center; gap:5px; padding:0; }
  .btn-ghost:hover { color:var(--text); }
  .summary-card { border:1px solid var(--border); border-radius:var(--radius); padding:1rem 1.25rem;
                  background:var(--surface); margin-bottom:1rem; }
  .summary-row { display:flex; justify-content:space-between; align-items:flex-start;
                 padding:7px 0; border-bottom:1px solid var(--border); font-size:13px; gap:12px; }
  .summary-row:last-child { border-bottom:none; }
  .summary-key { color:var(--muted); }
  .summary-val { font-weight:500; text-align:right; max-width:60%; }
  .code-block { font-size:11px; font-family:"SF Mono","Fira Code",monospace; background:#f0ede8;
                border-radius:var(--radius-sm); padding:12px 14px; color:var(--muted);
                white-space:pre-wrap; line-height:1.7; margin-bottom:1rem; overflow-x:auto; }
  .badge { display:inline-block; font-size:11px; font-weight:500; padding:2px 9px;
           border-radius:20px; background:var(--success-bg); color:var(--success); }
  .error-note { font-size:13px; color:#a32d2d; background:#fcebeb; padding:10px 14px;
                border-radius:var(--radius-sm); margin-bottom:1rem; display:none; }
  .result-panel { display:none; }
  .result-panel.visible { display:block; }
  .success-banner { background:var(--success-bg); color:var(--success); border-radius:var(--radius-sm);
                    padding:10px 14px; font-size:14px; font-weight:500; margin-bottom:1rem; }
  .endpoint-ref { font-size:12px; color:var(--muted); margin-top:1rem; line-height:1.8; }
  .endpoint-ref code { background:#f0ede8; padding:1px 6px; border-radius:4px; font-size:11px; }
  .upload-card { border:1px solid var(--border); border-radius:var(--radius); padding:1rem 1.25rem;
                 background:var(--surface); margin-bottom:1rem; }
  .upload-card h3 { font-size:16px; font-weight:500; margin-bottom:6px; }
  .upload-card p { font-size:13px; color:var(--muted); line-height:1.6; margin-bottom:1rem; }
  .file-input { width:100%; font-size:13px; padding:10px 12px; border:1px solid var(--border);
                border-radius:var(--radius-sm); background:var(--surface); color:var(--text); margin-bottom:10px; }
  .helper-text { font-size:12px; color:var(--muted); line-height:1.6; margin-top:8px; }
  .analysis-panel { display:none; margin-top:1rem; }
  .analysis-panel.visible { display:block; }
  .analysis-grid { display:grid; grid-template-columns:repeat(auto-fit, minmax(220px,1fr)); gap:10px; margin-bottom:1rem; }
  .metric-card { border:1px solid var(--border); border-radius:var(--radius-sm); background:#f9f8f5; padding:12px 14px; }
  .metric-label { font-size:11px; text-transform:uppercase; letter-spacing:.06em; color:var(--muted); margin-bottom:6px; }
  .metric-value { font-size:18px; font-weight:600; color:var(--text); }
  .analysis-section { border:1px solid var(--border); border-radius:var(--radius); background:var(--surface); padding:1rem 1.25rem; margin-bottom:1rem; }
  .analysis-section h3 { font-size:16px; font-weight:500; margin-bottom:10px; }
  .analysis-section h4 { font-size:13px; font-weight:600; margin:12px 0 6px; color:var(--text); }
  .analysis-list { margin:0; padding-left:18px; color:var(--text); }
  .analysis-list li { margin-bottom:6px; font-size:13px; line-height:1.6; }
  .pill-row { display:flex; flex-wrap:wrap; gap:8px; margin-top:8px; }
  .pill { display:inline-flex; align-items:center; gap:6px; padding:5px 10px; border-radius:999px; background:#f0ede8; color:var(--text); font-size:12px; }
  .component-card, .risk-card { border:1px solid var(--border); border-radius:var(--radius-sm); padding:12px 14px; background:#f9f8f5; margin-bottom:10px; }
  .component-head, .risk-head { display:flex; justify-content:space-between; gap:12px; align-items:flex-start; margin-bottom:6px; }
  .component-title, .risk-title { font-size:14px; font-weight:600; }
  .component-meta, .risk-meta { font-size:11px; color:var(--muted); text-transform:uppercase; letter-spacing:.05em; }
  .component-desc, .risk-desc { font-size:13px; color:var(--text); line-height:1.6; }
  .inline-code { background:#f0ede8; padding:1px 6px; border-radius:4px; font-size:11px; font-family:"SF Mono","Fira Code",monospace; }
</style>
</head>
<body>
<div class="shell">
  <div class="page-header">
    <h1>Scoping preferences</h1>
    <p>Configure scoping constraints so the analyser has accurate context — not assumptions.</p>
  </div>

  <div class="error-note" id="err"></div>

  <!-- Single Page Form -->
  <div class="step active" id="step1">
    <div class="step-title">Solution type & deployment</div>
    <div class="step-desc">This fundamentally changes the scoping pattern, component list, and estimation approach.</div>

    <div class="section">
      <div class="section-label">Build approach</div>
      <div class="option-grid">
        <div class="opt selected" onclick="pick(this,'approach','greenfield')"><div class="opt-label">Greenfield custom build</div><div class="opt-sub">Designed and built from scratch</div></div>
        <div class="opt" onclick="pick(this,'approach','packaged')"><div class="opt-label">Packaged solution</div><div class="opt-sub">SAP, Salesforce, ServiceNow…</div></div>
        <div class="opt" onclick="pick(this,'approach','extend')"><div class="opt-label">Extend existing system</div><div class="opt-sub">Add to or modernise a live system</div></div>
        <div class="opt" onclick="pick(this,'approach','hybrid')"><div class="opt-label">Hybrid</div><div class="opt-sub">Platform + custom extensions</div></div>
      </div>
      <div class="conditional" id="packaged-cond">
        <div class="section-label">Which platform?</div>
        <div class="tag-row">
          <span class="tag" onclick="toggleTag(this,'platform','salesforce')">Salesforce</span>
          <span class="tag" onclick="toggleTag(this,'platform','sap')">SAP</span>
          <span class="tag" onclick="toggleTag(this,'platform','servicenow')">ServiceNow</span>
          <span class="tag" onclick="toggleTag(this,'platform','ms365')">Microsoft 365</span>
          <span class="tag" onclick="toggleTag(this,'platform','oracle')">Oracle</span>
          <span class="tag" onclick="toggleTag(this,'platform','workday')">Workday</span>
          <span class="tag" onclick="toggleTag(this,'platform','other')">Other</span>
        </div>
      </div>
    </div>

    <div class="divider"></div>

    <div class="section">
      <div class="section-label">Deployment model</div>
      <div class="option-grid">
        <div class="opt selected" onclick="pick(this,'deployment','cloud')"><div class="opt-label">Cloud</div><div class="opt-sub">AWS, Azure, GCP</div></div>
        <div class="opt" onclick="pick(this,'deployment','on_prem')"><div class="opt-label">On-premise</div><div class="opt-sub">Client-managed infra</div></div>
        <div class="opt" onclick="pick(this,'deployment','hybrid')"><div class="opt-label">Hybrid</div><div class="opt-sub">Cloud + on-prem mix</div></div>
        <div class="opt" onclick="pick(this,'deployment','saas')"><div class="opt-label">SaaS</div><div class="opt-sub">Multi-tenant hosted</div></div>
      </div>
      <div class="conditional visible" id="cloud-cond">
        <div class="section-label">Preferred cloud provider</div>
        <div class="tag-row">
          <span class="tag" onclick="singleTag(this,'cloud','aws')">AWS</span>
          <span class="tag" onclick="singleTag(this,'cloud','azure')">Azure</span>
          <span class="tag" onclick="singleTag(this,'cloud','gcp')">GCP</span>
          <span class="tag" onclick="singleTag(this,'cloud','ibm_cloud')">IBM Cloud</span>
          <span class="tag" onclick="singleTag(this,'cloud','no_pref')">No preference</span>
        </div>
      </div>
    </div>

    <div class="divider"></div>

    <div class="step-title" style="margin-top:1.5rem">Technology landscape & delivery constraints</div>
    <div class="step-desc">Shapes the component complexity, integration patterns, and estimation risk profile.</div>

    <div class="section">
      <div class="section-label">Compliance regime (select all that apply)</div>
      <div class="tag-row">
        <span class="tag" onclick="toggleTag(this,'compliance','hipaa')">HIPAA</span>
        <span class="tag" onclick="toggleTag(this,'compliance','pci')">PCI DSS</span>
        <span class="tag" onclick="toggleTag(this,'compliance','fedramp')">FedRAMP</span>
        <span class="tag" onclick="toggleTag(this,'compliance','gdpr')">GDPR</span>
        <span class="tag" onclick="toggleTag(this,'compliance','sox')">SOX</span>
        <span class="tag" onclick="toggleTag(this,'compliance','iso27001')">ISO 27001</span>
        <span class="tag" onclick="toggleTag(this,'compliance','none')">None / TBD</span>
      </div>
    </div>
    <div class="divider"></div>

    <div class="section">
      <div class="section-label">Client channel requirements</div>
      <div class="tag-row">
        <span class="tag" onclick="toggleTag(this,'channels','web')">Web application</span>
        <span class="tag" onclick="toggleTag(this,'channels','mobile_native')">Native mobile (iOS/Android)</span>
        <span class="tag" onclick="toggleTag(this,'channels','pwa')">Progressive web app</span>
        <span class="tag" onclick="toggleTag(this,'channels','api_only')">API / headless only</span>
        <span class="tag" onclick="toggleTag(this,'channels','desktop')">Desktop app</span>
      </div>
    </div>
    <div class="divider"></div>

    <div class="section">
      <div class="section-label">Integration style preference</div>
      <div class="option-grid" style="grid-template-columns:repeat(auto-fit, minmax(155px,1fr))">
        <div class="opt" onclick="pick(this,'integration','rest')"><div class="opt-label">REST / API-first</div><div class="opt-sub">OpenAPI, RESTful</div></div>
        <div class="opt" onclick="pick(this,'integration','event')"><div class="opt-label">Event-driven</div><div class="opt-sub">Kafka, SQS, pub/sub</div></div>
        <div class="opt" onclick="pick(this,'integration','esb')"><div class="opt-label">ESB / Middleware</div><div class="opt-sub">MuleSoft, IBM MQ, TIBCO</div></div>
        <div class="opt" onclick="pick(this,'integration','fhir')"><div class="opt-label">HL7 FHIR</div><div class="opt-sub">Healthcare interop</div></div>
        <div class="opt selected" onclick="pick(this,'integration','no_pref')"><div class="opt-label">No preference</div><div class="opt-sub">Let requirements drive</div></div>
      </div>
    </div>
    <div class="divider"></div>

    <div class="section">
      <div class="section-label">Delivery timeline</div>
      <div class="option-grid">
        <div class="opt" onclick="pick(this,'timeline','fixed')"><div class="opt-label">Fixed deadline</div><div class="opt-sub">Hard go-live, no flex</div></div>
        <div class="opt" onclick="pick(this,'timeline','target')"><div class="opt-label">Target date</div><div class="opt-sub">Preferred, negotiable</div></div>
        <div class="opt" onclick="pick(this,'timeline','phased')"><div class="opt-label">Phased delivery</div><div class="opt-sub">MVP first, iterative</div></div>
        <div class="opt selected" onclick="pick(this,'timeline','tbd')"><div class="opt-label">TBD</div><div class="opt-sub">Not yet defined</div></div>
      </div>
    </div>
    <div class="divider"></div>

    <div class="section">
      <div class="section-label">Existing technology estate <span style="font-weight:400;color:var(--muted)">(optional)</span></div>
      <input class="text-input" id="tech-estate" type="text" placeholder="e.g. Azure AD, Oracle DB, MuleSoft, IBM MQ, existing EHR system…" />
      <div class="info-note">Mention identity providers, databases, integration platforms, or legacy systems the new solution must connect to.</div>
    </div>

    <div class="divider"></div>

    <div class="btn-row" style="margin-top:2rem">
      <span></span>
      <button class="btn btn-primary" id="submit-btn" onclick="submitPreferences()">Submit preferences &rarr;</button>
    </div>
  </div>

  <!-- Result -->
  <div class="result-panel" id="result-panel">
    <div class="success-banner">&#10003; Preferences validated & saved</div>
    <div class="summary-card">
      <div style="font-size:11px;font-weight:500;text-transform:uppercase;letter-spacing:.06em;color:var(--muted);margin-bottom:10px">Preferences summary</div>
      <div id="result-json"></div>
      <div class="helper-text" id="preferences-files" style="margin-top:10px"></div>
    </div>

    <div class="upload-card">
      <h3>Upload requirements markdown</h3>
      <p>Upload the markdown file containing your extracted requirements. The saved preferences will be reused automatically and sent forward for scoping generation.</p>
      <input class="file-input" id="requirements-file" type="file" accept=".md,.markdown,text/markdown,.txt" />
      <input class="text-input" id="project-name" type="text" placeholder="Project name (optional)" style="margin-bottom:10px;" />
      <div class="btn-row" style="margin-top:0">
        <span class="helper-text">Accepted formats: <span class="inline-code">.md</span>, <span class="inline-code">.markdown</span>, <span class="inline-code">.txt</span></span>
        <button class="btn btn-primary" id="analyze-btn" onclick="analyzeUploadedRequirements()">Generate scoping &rarr;</button>
      </div>
      <div class="helper-text" id="file-status"></div>
    </div>

    <div class="analysis-panel" id="analysis-panel">
      <div class="analysis-section">
        <h3>Saved scoping files</h3>
        <div class="helper-text" id="analysis-files"></div>
      </div>
    </div>

    <div class="endpoint-ref">
      Swagger docs: <a href="/docs" style="color:var(--accent)">/docs</a> &nbsp;·&nbsp; ReDoc: <a href="/redoc" style="color:var(--accent)">/redoc</a>
    </div>
  </div>
</div>

<script>
const S = { approach:'greenfield', deployment:'cloud', cloud:null, integration:'no_pref',
            timeline:'tbd', platform:[], compliance:[], channels:[] };
let savedPreferences = null;

function pick(el, g, v) {
  el.closest('.option-grid').querySelectorAll('.opt').forEach(e => e.classList.remove('selected'));
  el.classList.add('selected'); S[g] = v;
  if (g==='approach') document.getElementById('packaged-cond').className = 'conditional' + (v==='packaged'||v==='hybrid' ? ' visible' : '');
  if (g==='deployment') document.getElementById('cloud-cond').className = 'conditional' + (v==='cloud'||v==='hybrid' ? ' visible' : '');
}
function toggleTag(el, g, v) {
  if (!Array.isArray(S[g])) S[g] = [];
  if (v === 'none') {
    el.closest('.tag-row').querySelectorAll('.tag').forEach(t => t.classList.remove('selected'));
    S[g] = ['none'];
    el.classList.add('selected');
    return;
  }
  const tags = el.closest('.tag-row').querySelectorAll('.tag');
  let noneTag = null;
  tags.forEach(t => { if (t.getAttribute('onclick').includes(",'none'")) noneTag = t; });
  if (noneTag) noneTag.classList.remove('selected');
  S[g] = S[g].filter(x => x !== 'none');
  el.classList.toggle('selected');
  if (el.classList.contains('selected')) {
    if (!S[g].includes(v)) S[g].push(v);
  } else {
    S[g] = S[g].filter(x => x !== v);
  }
}
function singleTag(el, g, v) {
  el.closest('.tag-row').querySelectorAll('.tag').forEach(t => t.classList.remove('selected'));
  el.classList.add('selected');
  S[g] = v;
}
const LA = {
  approach:{greenfield:'Greenfield custom build',packaged:'Packaged solution',extend:'Extend existing system',hybrid:'Hybrid'},
  deployment:{cloud:'Cloud',on_prem:'On-premise',hybrid:'Hybrid',saas:'SaaS'},
  cloud:{aws:'AWS',azure:'Azure',gcp:'GCP',ibm_cloud:'IBM Cloud',no_pref:'No preference'},
  integration:{rest:'REST / API-first',event:'Event-driven',esb:'ESB / Middleware',fhir:'HL7 FHIR',no_pref:'TBD'},
  timeline:{fixed:'Fixed deadline',target:'Target date',phased:'Phased / MVP first',tbd:'TBD'},
  compliance:{hipaa:'HIPAA',pci:'PCI DSS',fedramp:'FedRAMP',gdpr:'GDPR',sox:'SOX',iso27001:'ISO 27001',none:'None / TBD'},
  channels:{web:'Web',mobile_native:'Native mobile',pwa:'PWA',api_only:'API/headless',desktop:'Desktop'},
  platform:{salesforce:'Salesforce',sap:'SAP',servicenow:'ServiceNow',ms365:'Microsoft 365',oracle:'Oracle',workday:'Workday',other:'Other'}
};
function escapeHtml(value) {
  const span = document.createElement('span');
  span.textContent = String(value ?? '');
  return span.innerHTML;
}
function buildPayload() {
  return {
    approach:S.approach,
    deployment:S.deployment,
    cloud:S.cloud,
    platform:S.platform,
    compliance:S.compliance,
    channels:S.channels,
    integration:S.integration,
    timeline:S.timeline,
    tech_estate:document.getElementById('tech-estate').value.trim()
  };
}
function setError(message) {
  const el = document.getElementById('err');
  if (el) {
    el.textContent = 'Error: ' + message;
    el.style.display = 'block';
  }
}
function clearError() {
  const el = document.getElementById('err');
  if (el) {
    el.style.display = 'none';
  }
}
function setFileStatus(message) {
  document.getElementById('file-status').textContent = message || '';
}
function renderMetrics(summary) {
  const metrics = [
    ['Domains', summary.domain_count ?? 0],
    ['Actors', summary.actor_count ?? 0],
    ['Components', summary.component_count ?? 0],
    ['Avg complexity', summary.avg_complexity ?? 'n/a'],
    ['Compliance impacted', summary.compliance_components ?? 0],
    ['Story points (mid)', summary.total_story_points_mid ?? 0],
  ];
  document.getElementById('analysis-metrics').innerHTML = metrics.map(([label, value]) => `
    <div class="metric-card">
      <div class="metric-label">${escapeHtml(label)}</div>
      <div class="metric-value">${escapeHtml(value)}</div>
    </div>
  `).join('');
}
function renderScoping(result) {
  const scoping = result.architecture || {};
  const summaryHtml = `
    <div><strong>${escapeHtml(scoping.recommended || 'Recommended pattern unavailable')}</strong></div>
    <div style="margin-top:8px">${escapeHtml(scoping.rationale || '')}</div>
    ${scoping.domain_note ? `<div style="margin-top:8px;color:var(--muted)">${escapeHtml(scoping.domain_note)}</div>` : ''}
  `;
  document.getElementById('scoping-summary').innerHTML = summaryHtml;
  document.getElementById('scoping-principles').innerHTML = (scoping.key_principles || []).map(item =>
    `<span class="pill">${escapeHtml(item)}</span>`
  ).join('');
}
function renderSystemContext(result) {
  const context = result.system_context || {};
  document.getElementById('system-context-desc').textContent = context.description || 'No system context returned.';
  document.getElementById('system-actors').innerHTML = (context.actors || []).map(actor =>
    `<span class="pill">${escapeHtml(actor.name)} · ${escapeHtml(actor.type)}</span>`
  ).join('') || '<span class="helper-text">No actors returned.</span>';
  document.getElementById('system-integrations').innerHTML = (context.integrations || []).map(item =>
    `<li>${escapeHtml(item)}</li>`
  ).join('') || '<li>No integrations returned.</li>';
}
function renderComponents(result) {
  const components = result.components || [];
  document.getElementById('components-list').innerHTML = components.length ? components.map(component => {
    const story = component.story_point_range
      ? `${component.story_point_range.low}/${component.story_point_range.mid}/${component.story_point_range.high} SP`
      : 'No estimate';
    const meta = [component.type, component.complexity, component.module].filter(Boolean).join(' · ');
    const deps = (component.dependencies || []).length
      ? `<div class="helper-text">Dependencies: ${escapeHtml(component.dependencies.join(', '))}</div>`
      : '';
    return `
      <div class="component-card">
        <div class="component-head">
          <div>
            <div class="component-title">${escapeHtml(component.name)}</div>
            <div class="component-meta">${escapeHtml(meta)}</div>
          </div>
          <div class="component-meta">${escapeHtml(story)}</div>
        </div>
        <div class="component-desc">${escapeHtml(component.description || '')}</div>
        ${deps}
      </div>
    `;
  }).join('') : '<div class="helper-text">No components returned.</div>';
}
function renderRisks(result) {
  const risks = result.risks || [];
  document.getElementById('risks-list').innerHTML = risks.length ? risks.map(risk => `
    <div class="risk-card">
      <div class="risk-head">
        <div class="risk-title">${escapeHtml(risk.risk)}</div>
        <div class="risk-meta">${escapeHtml(risk.level || 'unknown')}</div>
      </div>
      <div class="risk-desc">${escapeHtml(risk.mitigation || '')}</div>
    </div>
  `).join('') : '<div class="helper-text">No risks returned.</div>';
}
let currentArchitecture = null;

function renderKeyValueSummary(containerId, data) {
  const entries = Object.entries(data || {});
  document.getElementById(containerId).innerHTML = entries.length
    ? entries.map(([key, value]) => `
        <div class="summary-row">
          <span class="summary-key">${escapeHtml(key.replace(/_/g, ' '))}</span>
          <span class="summary-val">${escapeHtml(Array.isArray(value) ? value.join(', ') : value)}</span>
        </div>
      `).join('')
    : '<div class="helper-text">No summary available.</div>';
}
function renderSavedFiles(containerId, savedFiles) {
  // Only show the enriched JSON file
  const enrichedFile = savedFiles?.architecture_enriched;
  document.getElementById(containerId).innerHTML = enrichedFile
    ? `<div><strong>Architecture enriched:</strong> <span class="inline-code">${escapeHtml(enrichedFile)}</span></div>`
    : 'No enriched file available.';
}
function renderAnalysis(result) {
  renderSavedFiles('analysis-files', result.saved_files);
  document.getElementById('analysis-panel').classList.add('visible');
}
async function submitPreferences() {
  const btn = document.getElementById('submit-btn');
  if (!btn) {
    console.error('Submit button not found');
    return;
  }
  btn.disabled = true;
  btn.textContent = 'Submitting…';
  clearError();
  try {
    const payload = buildPayload();
    const res = await fetch('/api/preferences', {
      method:'POST',
      headers:{'Content-Type':'application/json'},
      body:JSON.stringify(payload)
    });
    const data = await res.json();
    if (!res.ok) throw new Error(data.detail || JSON.stringify(data));
    savedPreferences = payload;
    // Hide the form step and show the result panel
    const step1 = document.getElementById('step1');
    if (step1) step1.classList.remove('active');
    renderKeyValueSummary('result-json', data.summary || {});
    renderSavedFiles('preferences-files', data.saved_files);
    const analysisPanel = document.getElementById('analysis-panel');
    const resultPanel = document.getElementById('result-panel');
    if (analysisPanel) analysisPanel.classList.remove('visible');
    if (resultPanel) resultPanel.classList.add('visible');
    setFileStatus('Preferences saved. Upload a markdown file to continue.');
    btn.textContent = 'Preferences saved';
  } catch (e) {
    setError(e.message || String(e));
    btn.disabled = false;
    btn.textContent = 'Submit preferences →';
  }
}
async function analyzeUploadedRequirements() {
  clearError();
  if (!savedPreferences) {
    setError('Submit preferences before generating scoping.');
    return;
  }
  const fileInput = document.getElementById('requirements-file');
  const file = fileInput.files && fileInput.files[0];
  if (!file) {
    setError('Select a markdown file first.');
    return;
  }
  const analyzeBtn = document.getElementById('analyze-btn');
  analyzeBtn.disabled = true;
  analyzeBtn.textContent = 'Generating…';
  try {
    const requirements = await file.text();
    if (!requirements.trim()) {
      throw new Error('The selected file is empty.');
    }
    setFileStatus(`Loaded ${file.name} (${requirements.length} characters). Generating scoping…`);
    const projectName = document.getElementById('project-name').value.trim() || 'the system';
    const res = await fetch('/api/analyze', {
      method:'POST',
      headers:{'Content-Type':'application/json'},
      body:JSON.stringify({
        preferences: savedPreferences,
        requirements,
        project_name: projectName
      })
    });
    const data = await res.json();
    if (!res.ok) {
      const detail = data.detail || JSON.stringify(data);
      if (String(detail).includes('Could not resolve authentication method')) {
        throw new Error('Scoping generation currently requires a valid ANTHROPIC_API_KEY. The UI upload flow is working, but the backend scoping engine is still using the Anthropic client.');
      }
      if (String(detail).includes('Requirements must be at least 10 characters')) {
        throw new Error('The requirements file is too short or empty. Please upload a valid requirements file with at least 10 characters.');
      }
      if (res.status === 422) {
        throw new Error(`Validation error: ${detail}`);
      }
      throw new Error(detail);
    }
    renderAnalysis(data);
    setFileStatus(`Scoping generated from ${file.name}. Files saved under ${data.saved_files?.run_dir || 'outputs'}.`);
  } catch (e) {
    setError(e.message);
  } finally {
    analyzeBtn.disabled = false;
    analyzeBtn.textContent = 'Generate scoping →';
  }
}

</script>
</body>
</html>"""


# ── App factory ───────────────────────────────────────────────────────────────

def create_app() -> FastAPI:
    app = FastAPI(
        title="RFP Analyzer API",
        description=(
            "Phase 1.5 + Phase 2 of the RFP Analyzer pipeline.\n\n"
            "**Flow:**\n"
            "1. `GET /` — open the preferences intake form\n"
            "2. `POST /api/preferences` — validate & structure preferences\n"
            "3. `POST /api/analyze` — run full scoping analysis\n\n"
            "Set `ANTHROPIC_API_KEY` in your environment before calling `/api/analyze`."
        ),
        version="1.1.0",
        docs_url="/docs",
        redoc_url="/redoc",
    )

    # CORS — tighten origins in production
    app.add_middleware(
        CORSMiddleware,
        allow_origins=os.getenv("CORS_ORIGINS", "*").split(","),
        allow_methods=["GET", "POST"],
        allow_headers=["Content-Type", "Authorization"],
    )

    # Mount API routers
    app.include_router(router, prefix="/api", tags=["RFP Analyzer"])
    app.include_router(gsc_router, tags=["GSE (GreenStar Estimation Engine Input) Questionnaire"])

    # Serve preferences form at root
    @app.get("/", response_class=HTMLResponse, include_in_schema=False)
    async def serve_form() -> HTMLResponse:
        return HTMLResponse(content=_HTML_FORM)
    
    # Serve GSE questionnaire form
    @app.get("/gse", response_class=HTMLResponse, include_in_schema=False)
    async def serve_gse_form() -> HTMLResponse:
        gse_form_path = Path("gse-template/questionnaire_form.html")
        if gse_form_path.exists():
            return HTMLResponse(content=gse_form_path.read_text(encoding="utf-8"))
        return HTMLResponse(content="<h1>GSE Form not found</h1>", status_code=404)
    
    # Serve RFP to GSE Bridge
    @app.get("/bridge", response_class=HTMLResponse, include_in_schema=False)
    async def serve_bridge() -> HTMLResponse:
        bridge_path = Path("RFP_to_GSE_Bridge_v3.html")
        if bridge_path.exists():
            return HTMLResponse(content=bridge_path.read_text(encoding="utf-8"))
        return HTMLResponse(content="<h1>RFP to GSE Bridge not found</h1>", status_code=404)

    @app.on_event("startup")
    async def startup() -> None:
        logger.info("RFP Analyzer API started - docs at /docs")

    return app


# Singleton instance (used by uvicorn)
# Force reload: 2026-06-13 18:06
app = create_app()

# Made with Bob
